version: '3.4'

services:
  polisapp:
    image: cloud22.azurecr.io/polisapp/frontend:latest
    depends_on:
      - polisapi
    ports: 
      - "8080:80" 
    build:
      context: .
      dockerfile: PolisApp/Dockerfile
    networks:
      - apiconnection

  polisapi:
    image: cloud22.azurecr.io/polisapi/backend:latest
    ports:     
      - "8081:80"
    build:
      context: .
      dockerfile: PolisApi/Dockerfile
    networks:
      - apiconnection

networks:
    apiconnection:
       driver: bridge