services:

  polisapi:
    build:
      context: .
      dockerfile: PolisApi/Dockerfile
    image: frampt/polisapi
    container_name: polisapi
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - apiconnection
    restart: unless-stopped

  polisapp:
    build:
      context: .
      dockerfile: PolisApp/Dockerfile
    image: frampt/polisapp
    container_name: polisapp
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiBaseUrl=http://polisapi
    depends_on:
      - polisapi
    networks:
      - apiconnection
    restart: unless-stopped

networks:
  apiconnection:
    driver: bridge