version: '3.4'

services:
  polisapp:
    image: frampt/polisapp    
    depends_on:
      - "polisapi"
    ports: 
      - "8080:80"
    build:
      context: .
      dockerfile: PolisApp/Dockerfile
    networks:
      - apiconnection

  polisapi:
    image: frampt/polisapi
    ports: 
      - "8081:80"
    build:
      context: .
      dockerfile: PolisApi/Dockerfile
    networks:
      - apiconnection

networks:
    apiconnection:
       driver: bridge
