name: Trigger auto deployment for polisapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'Dockerfile/**'
    - '.github/workflows/polisapp-AutoDeployTrigger-ca2dcabe-7e67-45a3-8cf2-fedc3c3e470b.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.POLISAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}Dockerfile 
          registryUrl: cloud22.azurecr.io
          registryUsername: ${{ secrets.POLISAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.POLISAPP_REGISTRY_PASSWORD }}
          containerAppName: polisapp
          resourceGroup: labb-mikael-rg
          imageToBuild: cloud22.azurecr.io/frampt/frontend:${{ github.sha }}
          dockerfilePath: Dockerfile

     

